CREATE TABLE "cars" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plate" varchar,
  "manufacture" varchar,
  "model" varchar,
  "image" text,
  "rentPerDay" int,
  "capacity" int,
  "description" varchar,
  "availableAt" timestamp,
  "transmission" varchar,
  "available" bool,
  "type" varchar,
  "year" int,
  "created_at" timestamp DEFAULT 'now()',
  "update_at" timestamp DEFAULT 'now()',
  "deteteAt" timestamp
);

CREATE TABLE "options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "car_id" bigint,
  "created_at" timestamp DEFAULT 'now()',
  "update_at" timestamp DEFAULT 'now()',
  "deteteAt" timestamp
);

CREATE TABLE "specs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "car_id" bigint,
  "created_at" timestamp DEFAULT 'now()',
  "update_at" timestamp DEFAULT 'now()',
  "deteteAt" timestamp
);

ALTER TABLE "options" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");

ALTER TABLE "specs" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");
